### ISSUE TITLE
Docker repo not found

### ISSUE THREAD

**Issue by mojtabye** [adnanh/webhook-contrib#3]
Hi, I tried to pull image from docker hub but the image was not found :(
https://hub.docker.com/r/adnanh/webhook/

> Unable to find image 'adnanh/webhook:latest' locally
> docker: Error response from daemon: pull access denied for adnanh/webhook, repository does not exist or may require 'docker login'.

**Comment by mojtabye** [comment]
I used https://hub.docker.com/r/almir/webhook

**Comment by MichelDiz** [comment]
This example below is a Rancher-Compose. And it's working perfectly, it manages to download the image. You may be logged in to another Private Registry and maybe this is preventing you from using the Docker Hub.

```yml
version: '2'
services:
  almirWebhook:
    image: almir/webhook
    stdin_open: true
    working_dir: /var/scripts
    volumes:
    - scripts:/var/scripts/
    tty: true
    ports:
    - 9000:9000/tcp
    command:
    - -hooks
    - myhook.json
    - -verbose
    labels:
      io.rancher.container.pull_image: always

```
